version: '3.5'

services:
  elk:
    container_name: ${HOSTNAME}
    image: cortezaproject/elk:latest
    volumes:
      - elk-data:/var/lib/elasticsearch
    restart: on-failure
    environment:
      VIRTUAL_HOST:     ${HOSTNAME}
      VIRTUAL_PORT:     5601
      LETSENCRYPT_HOST: ${HOSTNAME}
    hostname: ${HOSTNAME}
    networks: [ proxy, elk ]

networks:
  proxy: { external: true }
  elk: { name: elk }

volumes: { elk-data: { driver: local } }
